EXPS_PATH: "./experiments"
DATASET_PATH: "./data/HD"
CLASS_LIST: ['Background',
        'Freespace',
        'PassableStep',
        'ImpassableStep',
        'ImpassableStep2',
        'Bump',
        'Line',
        'Vehicle',
        'Ego-Vehicle',
        'Pedestrian',
        'RoadMarker',
        'DisableMark',
        'Stopper',
        'Stopper-Occluded',
        'Bump',
        'Pillar']
IGNORE_CLASS: ['Background', 'Freespace']
IMAGENET_PRETRAINED_MODELS: "./pretrained_models/hrnet_w18_small_model_v2.pth"
